  radarr:
    image: linuxserver/radarr
    container_name: radarr
    env_file:
      - ./services/radarr/radarr.env
    volumes:
      - ./volumes/radarr/config:/config
      - /mnt/movies:/movies
      - ./volumes/sabnzbd/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
